version: '2.1'
services:

  configserver:
    build: configserver/.
    ports:
      - "8888:8080"
    links:
      - zipkin

  zuul:
    build: zuul/.
    ports:
      - "80:8080"
    links:
      - configserver
      - zipkin
      - admin

  frontend:
    build: frontend/.
    ports:
     - "8080:8080"
    links:
      - configserver
      - zipkin
      - admin
      - zuul

  soapclient:
    build: soapclient/.
    ports: 
      - "5050:8080"
    links:
      - configserver
      - zipkin
      - admin

  soapserver:
    build: soapserver/.
    ports:
      - "9090:8080"
    links:
      - configserver
      - database
      - zipkin
      - admin

  admin:
    build: admin/.
    ports:
      - "10060:8080"
    links:
      - zipkin

  database:
     image: postgres:9.6-alpine
     ports:  
       - "5432:5432"
     environment:
       - POSTGRES_PASSWORD=mysecretpassword
  
  zipkin:
     image: openzipkin/zipkin:1.26.0
     ports:
       - "9411:9411"    



