version: '2.1'
services:

  configserver:
    build: configserver/.
    ports:
      - "8888:8080"
    links:
      - zipkin
      - admin

  zuul:
    build: zuul/.
    ports:
      - "80:8080"
    links:
      - configserver
      - zipkin
      - admin

  frontend:
    build: frontend/.
    ports:
     - "8080:8080"
    links:
      - configserver
      - zipkin
      - admin
      - zuul

  soapclient:
    build: soapclient/.
    ports:
      - "5050:8080"
    links:
      - configserver
      - zipkin
      - admin


  admin:
    build: admin/.
    ports:
      - "10060:10060"


  zipkin:
     image: openzipkin/zipkin:1.26.0
     ports:
       - "9410:9410"
       - "9411:9411"
